openapi: 3.1.0
info:
  title: Bitwavie Processor
  version: 1.0.0
servers:
  - url: https://bitwavie-orchestrator-455488113475.us-central1.run.app

paths:
  /price/:
    get:
      operationId: getCryptoPrice
      summary: Get historical crypto price
      parameters:
        - name: fromSym
          in: query
          required: true
          schema: { type: string }
        - name: timestampSEC
          in: query
          required: true
          schema: { type: integer }
        - name: toFiat
          in: query
          schema: { type: string, default: "USD" }
        - name: service
          in: query
          schema: { type: string, default: "coinbase" }
        - name: resolution
          in: query
          schema: { type: string, default: "1d" }
        - name: timezone
          in: query
          schema: { type: string, default: "UTC" }
      responses:
        '200':
          description: Historical crypto price
          content:
            application/json:
              schema:
                type: object
                properties:
                  price:
                    type: number
                  asset:
                    type: string
                  timestamp:
                    type: integer

  /fifo/universal:
    post:
      operationId: runUniversalFifo
      summary: Process FIFO for combined wallet inventory
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                type: object
                properties:
                  dateTime:
                    type: string
                    format: date-time
                    description: Transaction date and time
                  walletId:
                    type: string
                    description: Wallet identifier
                  operation:
                    type: string
                    enum: [DEPOSIT, WITHDRAW, FEE]
                    description: Transaction operation type
                  type:
                    type: string
                    description: Transaction type (e.g., purchase, sale, transfer)
                  transactionId:
                    type: string
                    description: Unique transaction identifier
                  assetTicker:
                    type: string
                    description: Asset ticker symbol
                  assetAmount:
                    type: number
                    description: Amount of asset involved in transaction
                  assetvalueInBaseCurrency:
                    type: number
                    description: Value of asset in base currency
                  feeAmount:
                    type: number
                    description: Fee amount
                  feeAsset:
                    type: string
                    description: Fee asset ticker
                required:
                  - dateTime
                  - walletId
                  - operation
                  - type
                  - transactionId
                  - assetTicker
                  - assetAmount
                  - assetvalueInBaseCurrency
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
      responses:
        '200':
          description: Universal FIFO results
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  results:
                    type: array
                    items:
                      type: object

  /fifo/per_wallet:
    post:
      operationId: runPerWalletFifo
      summary: Process FIFO per wallet
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                type: object
                properties:
                  dateTime:
                    type: string
                    format: date-time
                    description: Transaction date and time
                  walletId:
                    type: string
                    description: Wallet identifier
                  operation:
                    type: string
                    enum: [DEPOSIT, WITHDRAW, FEE]
                    description: Transaction operation type
                  type:
                    type: string
                    description: Transaction type (e.g., purchase, sale, transfer)
                  transactionId:
                    type: string
                    description: Unique transaction identifier
                  assetTicker:
                    type: string
                    description: Asset ticker symbol
                  assetAmount:
                    type: number
                    description: Amount of asset involved in transaction
                  assetvalueInBaseCurrency:
                    type: number
                    description: Value of asset in base currency
                  feeAmount:
                    type: number
                    description: Fee amount
                  feeAsset:
                    type: string
                    description: Fee asset ticker
                required:
                  - dateTime
                  - walletId
                  - operation
                  - type
                  - transactionId
                  - assetTicker
                  - assetAmount
                  - assetvalueInBaseCurrency
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
      responses:
        '200':
          description: Per-wallet FIFO results
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  results:
                    type: array
                    items:
                      type: object
