openapi: 3.1.0
info:
  title: Bitwavie Processor
  version: 1.0.0
servers:
  - url: https://bitwavie-orchestrator-l6ztzqodca-uc.a.run.app

paths:
  /price:
    get:
      operationId: getCryptoPrice
      summary: Get cryptocurrency price
      responses:
        '200':
          description: Cryptocurrency price
          content:
            application/json:
              schema:
                type: object
                properties:
                  price:
                    type: object
                    properties:
                      value:
                        type: string
                  status:
                    type: string
                  message:
                    type: string

  /fifo/universal:
    post:
      operationId: runUniversalFifo
      summary: Process FIFO for combined wallet inventory
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                transactions:
                  type: array
                  items:
                    type: object
                    properties:
                      dateTime:
                        type: string
                        format: date-time
                      walletId:
                        type: string
                      operation:
                        type: string
                        enum: [DEPOSIT, WITHDRAW, FEE]
                      type:
                        type: string
                      transactionId:
                        type: string
                      assetTicker:
                        type: string
                      assetAmount:
                        type: number
                      assetvalueInBaseCurrency:
                        type: number
                      feeAmount:
                        type: number
                      feeAsset:
                        type: string
                    required:
                      - dateTime
                      - walletId
                      - operation
                      - type
                      - transactionId
                      - assetTicker
                      - assetAmount
                      - assetvalueInBaseCurrency
              required:
                - transactions
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
      responses:
        '200':
          description: Universal FIFO results
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  message:
                    type: string

  /fifo/per_wallet:
    post:
      operationId: runPerWalletFifo
      summary: Process FIFO per wallet
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                transactions:
                  type: array
                  items:
                    type: object
                    properties:
                      dateTime:
                        type: string
                        format: date-time
                      walletId:
                        type: string
                      operation:
                        type: string
                        enum: [DEPOSIT, WITHDRAW, FEE]
                      type:
                        type: string
                      transactionId:
                        type: string
                      assetTicker:
                        type: string
                      assetAmount:
                        type: number
                      assetvalueInBaseCurrency:
                        type: number
                      feeAmount:
                        type: number
                      feeAsset:
                        type: string
                    required:
                      - dateTime
                      - walletId
                      - operation
                      - type
                      - transactionId
                      - assetTicker
                      - assetAmount
                      - assetvalueInBaseCurrency
              required:
                - transactions
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
      responses:
        '200':
          description: Per-wallet FIFO results
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  message:
                    type: string
